name: Build and Deploy personal website
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - master
jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and build
        uses: actions/setup-node@v2
      - name: run next command
        continue-on-error: true
        run: |
          cd public/cv
          wget https://github.com/ziyixi/cv/raw/master/cv.pdf -O cv.pdf
          cd ../..
          yarn install
          yarn build
          yarn export
      - name: deploy to github page
        uses: peaceiris/actions-gh-pages@v3
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          user_name: 'ziyixi'
          user_email: 'ziyixi@mail.ustc.edu.cn'
