name: Build and Deploy personal website
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and build
        uses: actions/setup-node@v2
      - name: run next command
        continue-on-error: true
        run: |
          yarn install
          yarn build
          yarn export
      - name: deploy to github page
        uses: peaceiris/actions-gh-pages@v3
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          keep_files: true